
export const CaliCarterAnnTxData = [
  {
    txName: "Andrew Goldberg",
    whatUsed: "Credit",
    debit: "+$2,000,000.00",
    date: "Jan 25, 2024",
    color: "green",
  },
  {
    txName: "President of pch",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "Sept 20, 2023",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Sept 10, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Sept 04, 2023",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "Sept 01, 2000",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Aug 18, 2000",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Aug 17, 2000",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Aug 09, 1990",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Aug 7, 1990",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Aug 3, 1990",
    color: "green",
  },
];
